### ISSUE TITLE
Unable to login to Twitch

### ISSUE THREAD

**Issue by Tg-rX** [jeff502/Twitch-Prediction-Bot#1]
Lovely code by the way, as someone that has never used Python previously, this is exactly what I was looking for and almost got it to work. But ran into a slight issue:

The new Chrome window being opened has the message "**Chrome is being controlled by automated test software**" at the top. I'm not sure if that's the issue, but I am unable to login to Twitch. Twitch gives this message 
"**Your browser is not currently supported. Please use a [recommended browser]**(https://help.twitch.tv/s/article/supported-browsers) or learn more [here](https://help.twitch.tv/s/article/supported-browsers)"

I tried to fix the "controlled by automated test software" issue by using the Python solution suggested here: "https://help.applitools.com/hc/en-us/articles/360007189411--Chrome-is-being-controlled-by-automated-test-software-notification"

The message near the title bar disappears by applying the suggested code, but it still wouldn't let me login ('your browser is not supported...' message)

I am sorry if I have not followed the syntax or format of submitting an issue since I'm literally using github and Python for the very first time in my life. Hope I've made my query clear. 

Thank you for your time!

**Comment by jeff502** [comment]
That's an interesting new bug.  "Chrome is being controlled by automated test software" shouldn't be the direct cause of anything. This more looks like Twitch now using Fastly security. I'm unsure if their goal was to crack down on automation, or this is a byproduct. Normal users have reported being effected as well as of 6 months ago.


 A possible work around would be to use Chrome profiles. Take a look here: [https://stackoverflow.com/questions/75121695/problem-with-twitch-selenium-authorization](https://stackoverflow.com/questions/75121695/problem-with-twitch-selenium-authorization). Do feel free to share with me your project! I'd love to see it. Best of luck!

**Comment by Tg-rX** [comment]
> That's an interesting new bug. "Chrome is being controlled by automated test software" shouldn't be the direct cause of anything. This more looks like Twitch now using Fastly security. I'm unsure if their goal was to crack down on automation, or this is a byproduct. Normal users have reported being effected as well as of 6 months ago.
> 
> A possible work around would be to use Chrome profiles. Take a look here: https://stackoverflow.com/questions/75121695/problem-with-twitch-selenium-authorization. Do feel free to share with me your project! I'd love to see it. Best of luck!

It worked thanks :D 
But unfortunately **it doesn't bet any points**. Even with all other Chrome instances being closed, it launches the popout chat (with twitch logged in) and then doesn't bet on anything at the 1 minute mark. 
Might be something I messed up (although I haven't meddled with your placing bet part of the code). Will try again to fix it myself.

Thanks again !
